spring:
  application:
    name:
      accounts-microservice
  docker:
    compose:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://www.mykeycloak.com:8040/auth/realms/recipe-app
          jwk-set-uri: "${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs"

keycloak:
  server-url: https://www.mykeycloak.com:8040/auth
  realm: recipe-app
  admin-client-id: java-client
  admin-client-secret: RgiolwvRMgwlxRDO0W4KMC2dSXZhtqZn
  admin-user-username: danu.anastasia@ceiti.md
  admin-user-password: password

server:
  port: 8463
  ssl:
    key-alias: "recipessl"
    key-password: "SSLkeystorePASS1"
    key-store: "classpath:recipessl.pfx"
    key-store-password: "SSLkeystorePASS1"
    trust-store: "classpath:recipessl.pfx"
    trust-store-password: "SSLkeystorePASS1"
    enabled: true

# Logging (optional)
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs.yaml
  swagger-ui:
    path: /swagger-ui/index.html